"""Emergency_Schema_Fix

Revision ID: 4757badd7918
Revises: f9e8d7c6b5a4
Create Date: 2026-04-10 15:37:36.313406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4757badd7918'
down_revision: Union[str, Sequence[str], None] = 'f9e8d7c6b5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliberation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_type', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_deliberation_logs_created_at'), 'deliberation_logs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_guest_id'), 'deliberation_logs', ['guest_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_message_id'), 'deliberation_logs', ['message_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_property_id'), 'deliberation_logs', ['property_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_reservation_id'), 'deliberation_logs', ['reservation_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_session_id'), 'deliberation_logs', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_deliberation_logs_verdict_type'), 'deliberation_logs', ['verdict_type'], unique=False, schema='core')
    op.create_table('owners',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('tax_mailing_address', sa.Text(), nullable=False),
    sa.Column('primary_residence_state', sa.String(length=2), nullable=True),
    sa.Column('psychological_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_owners_legal_name', 'owners', ['legal_name'], unique=False, schema='crog_acquisition')
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('county_name', sa.String(length=100), server_default=sa.text("'Fannin'"), nullable=False),
    sa.Column('parcel_id', sa.String(length=100), nullable=False),
    sa.Column('geom', backend.models.acquisition.GeometryPolygon(), nullable=True),
    sa.Column('assessed_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('zoning_code', sa.String(length=50), nullable=True),
    sa.Column('is_waterfront', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_ridgeline', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', name='uq_acquisition_parcels_parcel_id'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_parcels_assessed', 'parcels', ['assessed_value'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_parcels_geom', 'parcels', ['geom'], unique=False, schema='crog_acquisition', postgresql_using='gist')
    op.create_table('device_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='iot_schema'
    )
    op.create_index(op.f('ix_iot_schema_device_events_created_at'), 'device_events', ['created_at'], unique=False, schema='iot_schema')
    op.create_index(op.f('ix_iot_schema_device_events_device_id'), 'device_events', ['device_id'], unique=False, schema='iot_schema')
    op.create_table('digital_twins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('property_id', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_event_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='iot_schema'
    )
    op.create_index(op.f('ix_iot_schema_digital_twins_device_id'), 'digital_twins', ['device_id'], unique=True, schema='iot_schema')
    op.create_index(op.f('ix_iot_schema_digital_twins_property_id'), 'digital_twins', ['property_id'], unique=False, schema='iot_schema')
    op.create_table('case_graph_nodes_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_reference_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_case_graph_nodes_v2_case_slug'), 'case_graph_nodes_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_graph_nodes_v2_entity_reference_id'), 'case_graph_nodes_v2', ['entity_reference_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_graph_nodes_v2_entity_type'), 'case_graph_nodes_v2', ['entity_type'], unique=False, schema='legal')
    op.create_table('case_statements_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('stated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_case_statements_v2_case_slug'), 'case_statements_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_statements_v2_doc_id'), 'case_statements_v2', ['doc_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_statements_v2_entity_id'), 'case_statements_v2', ['entity_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_statements_v2_stated_at'), 'case_statements_v2', ['stated_at'], unique=False, schema='legal')
    op.create_table('deposition_kill_sheets_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('deponent_entity', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('high_risk_topics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_sequence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_questions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_deposition_kill_sheets_v2_case_slug'), 'deposition_kill_sheets_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_deposition_kill_sheets_v2_deponent_entity'), 'deposition_kill_sheets_v2', ['deponent_entity'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_deposition_kill_sheets_v2_status'), 'deposition_kill_sheets_v2', ['status'], unique=False, schema='legal')
    op.create_table('discovery_draft_packs_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('target_entity', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_discovery_draft_packs_v2_case_slug'), 'discovery_draft_packs_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_discovery_draft_packs_v2_status'), 'discovery_draft_packs_v2', ['status'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_discovery_draft_packs_v2_target_entity'), 'discovery_draft_packs_v2', ['target_entity'], unique=False, schema='legal')
    op.create_table('distillation_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_hash', sa.String(length=128), nullable=False),
    sa.Column('frontier_insight', sa.Text(), nullable=False),
    sa.Column('local_correction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_distillation_memory_context_hash'), 'distillation_memory', ['context_hash'], unique=True, schema='legal')
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_entities_name'), 'entities', ['name'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_entities_type'), 'entities', ['type'], unique=False, schema='legal')
    op.create_table('legal_exemplars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rationale_context', sa.Text(), nullable=False),
    sa.Column('perfect_output', sa.Text(), nullable=False),
    sa.Column('source_model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_legal_exemplars_category'), 'legal_exemplars', ['category'], unique=False, schema='legal')
    op.create_table('sanctions_alerts_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('contradiction_summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_sanctions_alerts_v2_alert_type'), 'sanctions_alerts_v2', ['alert_type'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_sanctions_alerts_v2_case_slug'), 'sanctions_alerts_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_sanctions_alerts_v2_confidence_score'), 'sanctions_alerts_v2', ['confidence_score'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_sanctions_alerts_v2_status'), 'sanctions_alerts_v2', ['status'], unique=False, schema='legal')
    op.create_table('sanctions_tripwire_runs_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('trigger_source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('alerts_found', sa.Integer(), nullable=False),
    sa.Column('alerts_saved', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_sanctions_tripwire_runs_v2_case_slug'), 'sanctions_tripwire_runs_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_sanctions_tripwire_runs_v2_status'), 'sanctions_tripwire_runs_v2', ['status'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_sanctions_tripwire_runs_v2_trigger_source'), 'sanctions_tripwire_runs_v2', ['trigger_source'], unique=False, schema='legal')
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('typography_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stock_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='verses_schema'
    )
    op.create_index(op.f('ix_verses_schema_products_sku'), 'products', ['sku'], unique=True, schema='verses_schema')
    op.create_table('owner_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_dnc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("contact_type IN ('CELL', 'LANDLINE', 'EMAIL')", name='ck_acquisition_owner_contacts_contact_type'),
    sa.CheckConstraint('confidence_score >= 0.00 AND confidence_score <= 1.00', name='ck_acquisition_owner_contacts_confidence_score'),
    sa.ForeignKeyConstraint(['owner_id'], ['crog_acquisition.owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_value', name='uq_acquisition_owner_contacts_owner_value'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_owner_contacts_owner', 'owner_contacts', ['owner_id'], unique=False, schema='crog_acquisition')
    op.create_table('properties',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('fannin_str_cert_id', sa.String(length=100), nullable=True),
    sa.Column('blue_ridge_str_permit', sa.String(length=100), nullable=True),
    sa.Column('zillow_zpid', sa.String(length=100), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('airbnb_listing_id', sa.String(length=100), nullable=True),
    sa.Column('vrbo_listing_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('UNMANAGED', 'CROG_MANAGED', 'COMPETITOR_MANAGED', 'FOR_SALE', name='market_state', schema='crog_acquisition'), server_default=sa.text("'UNMANAGED'"), nullable=False),
    sa.Column('management_company', sa.String(length=255), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('projected_adr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('projected_annual_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['crog_acquisition.owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['crog_acquisition.parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airbnb_listing_id'),
    sa.UniqueConstraint('blue_ridge_str_permit'),
    sa.UniqueConstraint('fannin_str_cert_id'),
    sa.UniqueConstraint('google_place_id'),
    sa.UniqueConstraint('vrbo_listing_id'),
    sa.UniqueConstraint('zillow_zpid'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_properties_mgmt', 'properties', ['management_company'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_properties_status', 'properties', ['status'], unique=False, schema='crog_acquisition')
    op.create_index(op.f('ix_crog_acquisition_properties_owner_id'), 'properties', ['owner_id'], unique=False, schema='crog_acquisition')
    op.create_index(op.f('ix_crog_acquisition_properties_parcel_id'), 'properties', ['parcel_id'], unique=False, schema='crog_acquisition')
    op.create_table('case_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('nas_path', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('sha256_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal.entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_case_evidence_case_slug'), 'case_evidence', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_evidence_entity_id'), 'case_evidence', ['entity_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_evidence_qdrant_point_id'), 'case_evidence', ['qdrant_point_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_evidence_sha256_hash'), 'case_evidence', ['sha256_hash'], unique=False, schema='legal')
    op.create_table('case_graph_edges_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['legal.case_graph_nodes_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['legal.case_graph_nodes_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_case_graph_edges_v2_case_slug'), 'case_graph_edges_v2', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_graph_edges_v2_source_evidence_id'), 'case_graph_edges_v2', ['source_evidence_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_graph_edges_v2_source_node_id'), 'case_graph_edges_v2', ['source_node_id'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_case_graph_edges_v2_target_node_id'), 'case_graph_edges_v2', ['target_node_id'], unique=False, schema='legal')
    op.create_table('discovery_draft_items_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rationale_from_graph', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('lethality_score', sa.Integer(), nullable=True),
    sa.Column('proportionality_score', sa.Integer(), nullable=True),
    sa.Column('correction_notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['legal.discovery_draft_packs_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_discovery_draft_items_v2_category'), 'discovery_draft_items_v2', ['category'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_discovery_draft_items_v2_pack_id'), 'discovery_draft_items_v2', ['pack_id'], unique=False, schema='legal')
    op.create_table('acquisition_pipeline',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('RADAR', 'TARGET_LOCKED', 'DEPLOYED', 'ENGAGED', 'ACQUIRED', 'REJECTED', name='funnel_stage', schema='crog_acquisition'), server_default=sa.text("'RADAR'"), nullable=False),
    sa.Column('llm_viability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('lob_mail_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instantly_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('vapi_call_status', sa.String(length=100), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['crog_acquisition.properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', name='uq_acquisition_pipeline_property_id'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_pipeline_next_action_date', 'acquisition_pipeline', ['next_action_date'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_pipeline_stage', 'acquisition_pipeline', ['stage'], unique=False, schema='crog_acquisition')
    op.create_table('intel_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('raw_source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['crog_acquisition.properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_intel_event_type', 'intel_events', ['event_type'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_intel_property_time', 'intel_events', ['property_id', 'detected_at'], unique=False, schema='crog_acquisition')
    op.create_table('str_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('signal_source', sa.Enum('FOIA_CSV', 'OTA_FIRECRAWL_HEURISTIC', 'AGGREGATOR_API', name='signal_source', schema='crog_acquisition'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.00 AND confidence_score <= 1.00', name='ck_acquisition_str_signals_confidence_score'),
    sa.ForeignKeyConstraint(['property_id'], ['crog_acquisition.properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='crog_acquisition'
    )
    op.create_index('idx_acquisition_str_signals_detected_at', 'str_signals', ['detected_at'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_str_signals_property', 'str_signals', ['property_id'], unique=False, schema='crog_acquisition')
    op.create_index('idx_acquisition_str_signals_source', 'str_signals', ['signal_source'], unique=False, schema='crog_acquisition')
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_slug', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['legal.case_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='legal'
    )
    op.create_index(op.f('ix_legal_timeline_events_case_slug'), 'timeline_events', ['case_slug'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_timeline_events_event_date'), 'timeline_events', ['event_date'], unique=False, schema='legal')
    op.create_index(op.f('ix_legal_timeline_events_source_evidence_id'), 'timeline_events', ['source_evidence_id'], unique=False, schema='legal')
    op.drop_index(op.f('ix_journal_line_items_journal_entry_id'), table_name='journal_line_items')
    op.drop_table('journal_line_items')
    op.drop_index(op.f('ix_parity_audits_confirmation_id'), table_name='parity_audits')
    op.drop_index(op.f('ix_parity_audits_reservation_id'), table_name='parity_audits')
    op.drop_index(op.f('ix_parity_audits_status'), table_name='parity_audits')
    op.drop_table('parity_audits')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_management_splits_property_id'), table_name='management_splits')
    op.drop_table('management_splits')
    op.drop_index(op.f('ix_activities_activity_slug'), table_name='activities')
    op.drop_index(op.f('ix_activities_slug'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_agent_runs_agent_status_started'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_trigger_source'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_trigger_status_started'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_trust_decisions_run_status'), table_name='trust_decisions')
    op.drop_index(op.f('ix_trust_decisions_status'), table_name='trust_decisions')
    op.drop_table('trust_decisions')
    op.drop_index(op.f('ix_operator_overrides_escalation_timestamp'), table_name='operator_overrides')
    op.drop_index(op.f('ix_operator_overrides_operator_email'), table_name='operator_overrides')
    op.drop_index(op.f('ix_operator_overrides_operator_timestamp'), table_name='operator_overrides')
    op.drop_index(op.f('ix_operator_overrides_timestamp'), table_name='operator_overrides')
    op.drop_table('operator_overrides')
    op.drop_index(op.f('ix_trust_transactions_decision_timestamp'), table_name='trust_transactions')
    op.drop_index(op.f('ix_trust_transactions_previous_signature'), table_name='trust_transactions')
    op.drop_index(op.f('ix_trust_transactions_timestamp'), table_name='trust_transactions')
    op.drop_table('trust_transactions')
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_vault_audit_logs_action'), table_name='vault_audit_logs')
    op.drop_index(op.f('ix_vault_audit_logs_created_at'), table_name='vault_audit_logs')
    op.drop_index(op.f('ix_vault_audit_logs_user_id'), table_name='vault_audit_logs')
    op.drop_table('vault_audit_logs')
    op.drop_index(op.f('ix_agent_registry_is_active'), table_name='agent_registry')
    op.drop_index(op.f('ix_agent_registry_name'), table_name='agent_registry')
    op.drop_index(op.f('ix_agent_registry_role'), table_name='agent_registry')
    op.drop_table('agent_registry')
    op.drop_index(op.f('ix_trust_accounts_name'), table_name='trust_accounts')
    op.drop_index(op.f('ix_trust_accounts_type'), table_name='trust_accounts')
    op.drop_index(op.f('ix_trust_accounts_type_name'), table_name='trust_accounts')
    op.drop_table('trust_accounts')
    op.drop_index(op.f('ix_taxonomy_categories_slug'), table_name='taxonomy_categories')
    op.drop_table('taxonomy_categories')
    op.drop_index(op.f('ix_swarm_escalations_reason_code'), table_name='swarm_escalations')
    op.drop_index(op.f('ix_swarm_escalations_status'), table_name='swarm_escalations')
    op.drop_index(op.f('ix_swarm_escalations_status_reason'), table_name='swarm_escalations')
    op.drop_table('swarm_escalations')
    op.drop_index(op.f('ix_legacy_pages_slug'), table_name='legacy_pages')
    op.drop_table('legacy_pages')
    op.drop_index(op.f('ix_journal_entries_property_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_reference'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_trust_ledger_entries_account_id'), table_name='trust_ledger_entries')
    op.drop_index(op.f('ix_trust_ledger_entries_entry_type'), table_name='trust_ledger_entries')
    op.drop_index(op.f('ix_trust_ledger_entries_transaction_id'), table_name='trust_ledger_entries')
    op.drop_table('trust_ledger_entries')
    op.drop_index(op.f('ix_pending_sync_reservation_id'), table_name='pending_sync')
    op.drop_index(op.f('ix_pending_sync_status'), table_name='pending_sync')
    op.drop_table('pending_sync')
    op.drop_index(op.f('ix_marketing_articles_category_id'), table_name='marketing_articles')
    op.drop_index(op.f('ix_marketing_articles_published_date'), table_name='marketing_articles')
    op.drop_index(op.f('ix_marketing_articles_slug'), table_name='marketing_articles')
    op.drop_table('marketing_articles')
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('ix_functional_nodes_canonical_path'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_content_category'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_crawl_status'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_cutover_status'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_functional_complexity'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_is_published'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_legacy_node_id'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_mirror_status'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_node_type'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_priority_tier'), table_name='functional_nodes')
    op.drop_index(op.f('ix_functional_nodes_source_path'), table_name='functional_nodes')
    op.drop_table('functional_nodes')
    op.alter_column('fees', 'flat_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('learned_rules', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learned_rules', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learned_rules', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learned_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learned_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('properties', 'city_limits',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('shadow_discrepancies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shadow_discrepancies', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shadow_discrepancies', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shadow_discrepancies', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('shadow_discrepancies', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('shadow_discrepancies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('properties', 'city_limits',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('learned_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('learned_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('learned_rules', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending_approval'::character varying"),
               existing_nullable=False)
    op.alter_column('learned_rules', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('learned_rules', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('fees', 'flat_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.create_table('functional_nodes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('legacy_node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('canonical_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content_category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('functional_complexity', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('crawl_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mirror_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cutover_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('priority_tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('http_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_text_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('form_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('taxonomy_terms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('media_refs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('mirror_component_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('mirror_route_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('source_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_crawled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('functional_nodes_pkey'))
    )
    op.create_index(op.f('ix_functional_nodes_source_path'), 'functional_nodes', ['source_path'], unique=True)
    op.create_index(op.f('ix_functional_nodes_priority_tier'), 'functional_nodes', ['priority_tier'], unique=False)
    op.create_index(op.f('ix_functional_nodes_node_type'), 'functional_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_functional_nodes_mirror_status'), 'functional_nodes', ['mirror_status'], unique=False)
    op.create_index(op.f('ix_functional_nodes_legacy_node_id'), 'functional_nodes', ['legacy_node_id'], unique=False)
    op.create_index(op.f('ix_functional_nodes_is_published'), 'functional_nodes', ['is_published'], unique=False)
    op.create_index(op.f('ix_functional_nodes_functional_complexity'), 'functional_nodes', ['functional_complexity'], unique=False)
    op.create_index(op.f('ix_functional_nodes_cutover_status'), 'functional_nodes', ['cutover_status'], unique=False)
    op.create_index(op.f('ix_functional_nodes_crawl_status'), 'functional_nodes', ['crawl_status'], unique=False)
    op.create_index(op.f('ix_functional_nodes_content_category'), 'functional_nodes', ['content_category'], unique=False)
    op.create_index(op.f('ix_functional_nodes_canonical_path'), 'functional_nodes', ['canonical_path'], unique=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('marketing_articles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_body_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('published_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], name=op.f('marketing_articles_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('marketing_articles_pkey'))
    )
    op.create_index(op.f('ix_marketing_articles_slug'), 'marketing_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_marketing_articles_published_date'), 'marketing_articles', ['published_date'], unique=False)
    op.create_index(op.f('ix_marketing_articles_category_id'), 'marketing_articles', ['category_id'], unique=False)
    op.create_table('pending_sync',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=50), server_default=sa.text("'create_reservation'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_sync_pkey'))
    )
    op.create_index(op.f('ix_pending_sync_status'), 'pending_sync', ['status'], unique=False)
    op.create_index(op.f('ix_pending_sync_reservation_id'), 'pending_sync', ['reservation_id'], unique=False)
    op.create_table('trust_ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.CheckConstraint("entry_type::text = ANY (ARRAY['debit'::character varying, 'credit'::character varying]::text[])", name=op.f('trust_ledger_entry_type')),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_trust_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['trust_accounts.id'], name=op.f('trust_ledger_entries_account_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['trust_transactions.id'], name=op.f('trust_ledger_entries_transaction_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trust_ledger_entries_pkey'))
    )
    op.create_index(op.f('ix_trust_ledger_entries_transaction_id'), 'trust_ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_trust_ledger_entries_entry_type'), 'trust_ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_trust_ledger_entries_account_id'), 'trust_ledger_entries', ['account_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_void', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('posted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_system', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey'))
    )
    op.create_index(op.f('ix_journal_entries_reference'), 'journal_entries', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_property_id'), 'journal_entries', ['property_id'], unique=False)
    op.create_table('legacy_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_format', sa.VARCHAR(length=50), server_default=sa.text("'full_html'::character varying"), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), server_default=sa.text("'node'::character varying"), autoincrement=False, nullable=True),
    sa.Column('bundle', sa.VARCHAR(length=100), server_default=sa.text("'page'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('legacy_pages_pkey'))
    )
    op.create_index(op.f('ix_legacy_pages_slug'), 'legacy_pages', ['slug'], unique=True)
    op.create_table('swarm_escalations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('decision_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'resolved'::character varying]::text[])", name=op.f('swarm_escalation_status')),
    sa.ForeignKeyConstraint(['decision_id'], ['trust_decisions.id'], name=op.f('swarm_escalations_decision_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('swarm_escalations_pkey')),
    sa.UniqueConstraint('decision_id', name=op.f('swarm_escalations_decision_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_swarm_escalations_status_reason'), 'swarm_escalations', ['status', 'reason_code'], unique=False)
    op.create_index(op.f('ix_swarm_escalations_status'), 'swarm_escalations', ['status'], unique=False)
    op.create_index(op.f('ix_swarm_escalations_reason_code'), 'swarm_escalations', ['reason_code'], unique=False)
    op.create_table('taxonomy_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('taxonomy_categories_pkey'))
    )
    op.create_index(op.f('ix_taxonomy_categories_slug'), 'taxonomy_categories', ['slug'], unique=True)
    op.create_table('trust_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.CheckConstraint("type::text = ANY (ARRAY['asset'::character varying, 'liability'::character varying]::text[])", name=op.f('trust_account_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('trust_accounts_pkey')),
    sa.UniqueConstraint('name', name=op.f('uq_trust_accounts_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_trust_accounts_type_name'), 'trust_accounts', ['type', 'name'], unique=False)
    op.create_index(op.f('ix_trust_accounts_type'), 'trust_accounts', ['type'], unique=False)
    op.create_index(op.f('ix_trust_accounts_name'), 'trust_accounts', ['name'], unique=False)
    op.create_table('agent_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('scope_boundary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('daily_tool_budget', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('daily_tool_budget >= 0', name=op.f('ck_agent_registry_daily_tool_budget_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_registry_pkey')),
    sa.UniqueConstraint('name', name=op.f('uq_agent_registry_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_agent_registry_role'), 'agent_registry', ['role'], unique=False)
    op.create_index(op.f('ix_agent_registry_name'), 'agent_registry', ['name'], unique=False)
    op.create_index(op.f('ix_agent_registry_is_active'), 'agent_registry', ['is_active'], unique=False)
    op.create_table('vault_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filters_applied', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_score', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vault_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_vault_audit_logs_user_id'), 'vault_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_vault_audit_logs_created_at'), 'vault_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_vault_audit_logs_action'), 'vault_audit_logs', ['action'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'published'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_promoted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_sticky', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blogs_pkey'))
    )
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.create_table('trust_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('streamline_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('decision_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('previous_signature', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['trust_decisions.id'], name=op.f('trust_transactions_decision_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('trust_transactions_pkey')),
    sa.UniqueConstraint('signature', name=op.f('uq_trust_transactions_signature'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('streamline_event_id', name=op.f('uq_trust_transactions_streamline_event_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_trust_transactions_timestamp'), 'trust_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trust_transactions_previous_signature'), 'trust_transactions', ['previous_signature'], unique=False)
    op.create_index(op.f('ix_trust_transactions_decision_timestamp'), 'trust_transactions', ['decision_id', 'timestamp'], unique=False)
    op.create_table('operator_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('escalation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operator_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('override_action', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('final_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("override_action::text = ANY (ARRAY['approve'::character varying, 'reject'::character varying, 'modify'::character varying]::text[])", name=op.f('operator_override_action')),
    sa.ForeignKeyConstraint(['escalation_id'], ['swarm_escalations.id'], name=op.f('operator_overrides_escalation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('operator_overrides_pkey'))
    )
    op.create_index(op.f('ix_operator_overrides_timestamp'), 'operator_overrides', ['timestamp'], unique=False)
    op.create_index(op.f('ix_operator_overrides_operator_timestamp'), 'operator_overrides', ['operator_email', 'timestamp'], unique=False)
    op.create_index(op.f('ix_operator_overrides_operator_email'), 'operator_overrides', ['operator_email'], unique=False)
    op.create_index(op.f('ix_operator_overrides_escalation_timestamp'), 'operator_overrides', ['escalation_id', 'timestamp'], unique=False)
    op.create_table('trust_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposed_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('deterministic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('policy_evaluation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['auto_approved'::character varying, 'escalated'::character varying, 'blocked'::character varying]::text[])", name=op.f('trust_decision_status')),
    sa.CheckConstraint('deterministic_score >= 0::double precision', name=op.f('ck_trust_decisions_deterministic_score_nonnegative')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('trust_decisions_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trust_decisions_pkey'))
    )
    op.create_index(op.f('ix_trust_decisions_status'), 'trust_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_trust_decisions_run_status'), 'trust_decisions', ['run_id', 'status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['queued'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'escalated'::character varying, 'blocked'::character varying]::text[])", name=op.f('agent_run_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], name=op.f('agent_runs_agent_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_runs_pkey'))
    )
    op.create_index(op.f('ix_agent_runs_trigger_status_started'), 'agent_runs', ['trigger_source', 'status', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_trigger_source'), 'agent_runs', ['trigger_source'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_status_started'), 'agent_runs', ['agent_id', 'status', 'started_at'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activity_slug', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activity_type_tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('area_tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('people_tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('difficulty_level_tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('season_tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('featured_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('featured_image_alt', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('featured_image_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('video_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'published'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('drupal_nid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drupal_vid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey'))
    )
    op.create_index(op.f('ix_activities_slug'), 'activities', ['slug'], unique=True)
    op.create_index(op.f('ix_activities_activity_slug'), 'activities', ['activity_slug'], unique=True)
    op.create_table('management_splits',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('owner_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('pm_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('management_splits_pkey')),
    sa.UniqueConstraint('property_id', name=op.f('uq_management_splits_property_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_management_splits_property_id'), 'management_splits', ['property_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('code', name=op.f('uq_accounts_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_table('parity_audits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confirmation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('local_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('streamline_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('delta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('local_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('streamline_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('parity_audits_pkey'))
    )
    op.create_index(op.f('ix_parity_audits_status'), 'parity_audits', ['status'], unique=False)
    op.create_index(op.f('ix_parity_audits_reservation_id'), 'parity_audits', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_parity_audits_confirmation_id'), 'parity_audits', ['confirmation_id'], unique=False)
    op.create_table('journal_line_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('debit', sa.NUMERIC(precision=18, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('credit', sa.NUMERIC(precision=18, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('journal_line_items_account_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('journal_line_items_journal_entry_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_line_items_pkey'))
    )
    op.create_index(op.f('ix_journal_line_items_journal_entry_id'), 'journal_line_items', ['journal_entry_id'], unique=False)
    op.drop_index(op.f('ix_legal_timeline_events_source_evidence_id'), table_name='timeline_events', schema='legal')
    op.drop_index(op.f('ix_legal_timeline_events_event_date'), table_name='timeline_events', schema='legal')
    op.drop_index(op.f('ix_legal_timeline_events_case_slug'), table_name='timeline_events', schema='legal')
    op.drop_table('timeline_events', schema='legal')
    op.drop_index('idx_acquisition_str_signals_source', table_name='str_signals', schema='crog_acquisition')
    op.drop_index('idx_acquisition_str_signals_property', table_name='str_signals', schema='crog_acquisition')
    op.drop_index('idx_acquisition_str_signals_detected_at', table_name='str_signals', schema='crog_acquisition')
    op.drop_table('str_signals', schema='crog_acquisition')
    op.drop_index('idx_acquisition_intel_property_time', table_name='intel_events', schema='crog_acquisition')
    op.drop_index('idx_acquisition_intel_event_type', table_name='intel_events', schema='crog_acquisition')
    op.drop_table('intel_events', schema='crog_acquisition')
    op.drop_index('idx_acquisition_pipeline_stage', table_name='acquisition_pipeline', schema='crog_acquisition')
    op.drop_index('idx_acquisition_pipeline_next_action_date', table_name='acquisition_pipeline', schema='crog_acquisition')
    op.drop_table('acquisition_pipeline', schema='crog_acquisition')
    op.drop_index(op.f('ix_legal_discovery_draft_items_v2_pack_id'), table_name='discovery_draft_items_v2', schema='legal')
    op.drop_index(op.f('ix_legal_discovery_draft_items_v2_category'), table_name='discovery_draft_items_v2', schema='legal')
    op.drop_table('discovery_draft_items_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_edges_v2_target_node_id'), table_name='case_graph_edges_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_edges_v2_source_node_id'), table_name='case_graph_edges_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_edges_v2_source_evidence_id'), table_name='case_graph_edges_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_edges_v2_case_slug'), table_name='case_graph_edges_v2', schema='legal')
    op.drop_table('case_graph_edges_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_evidence_sha256_hash'), table_name='case_evidence', schema='legal')
    op.drop_index(op.f('ix_legal_case_evidence_qdrant_point_id'), table_name='case_evidence', schema='legal')
    op.drop_index(op.f('ix_legal_case_evidence_entity_id'), table_name='case_evidence', schema='legal')
    op.drop_index(op.f('ix_legal_case_evidence_case_slug'), table_name='case_evidence', schema='legal')
    op.drop_table('case_evidence', schema='legal')
    op.drop_index(op.f('ix_crog_acquisition_properties_parcel_id'), table_name='properties', schema='crog_acquisition')
    op.drop_index(op.f('ix_crog_acquisition_properties_owner_id'), table_name='properties', schema='crog_acquisition')
    op.drop_index('idx_acquisition_properties_status', table_name='properties', schema='crog_acquisition')
    op.drop_index('idx_acquisition_properties_mgmt', table_name='properties', schema='crog_acquisition')
    op.drop_table('properties', schema='crog_acquisition')
    op.drop_index('idx_acquisition_owner_contacts_owner', table_name='owner_contacts', schema='crog_acquisition')
    op.drop_table('owner_contacts', schema='crog_acquisition')
    op.drop_index(op.f('ix_verses_schema_products_sku'), table_name='products', schema='verses_schema')
    op.drop_table('products', schema='verses_schema')
    op.drop_index(op.f('ix_legal_sanctions_tripwire_runs_v2_trigger_source'), table_name='sanctions_tripwire_runs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_tripwire_runs_v2_status'), table_name='sanctions_tripwire_runs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_tripwire_runs_v2_case_slug'), table_name='sanctions_tripwire_runs_v2', schema='legal')
    op.drop_table('sanctions_tripwire_runs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_alerts_v2_status'), table_name='sanctions_alerts_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_alerts_v2_confidence_score'), table_name='sanctions_alerts_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_alerts_v2_case_slug'), table_name='sanctions_alerts_v2', schema='legal')
    op.drop_index(op.f('ix_legal_sanctions_alerts_v2_alert_type'), table_name='sanctions_alerts_v2', schema='legal')
    op.drop_table('sanctions_alerts_v2', schema='legal')
    op.drop_index(op.f('ix_legal_legal_exemplars_category'), table_name='legal_exemplars', schema='legal')
    op.drop_table('legal_exemplars', schema='legal')
    op.drop_index(op.f('ix_legal_entities_type'), table_name='entities', schema='legal')
    op.drop_index(op.f('ix_legal_entities_name'), table_name='entities', schema='legal')
    op.drop_table('entities', schema='legal')
    op.drop_index(op.f('ix_legal_distillation_memory_context_hash'), table_name='distillation_memory', schema='legal')
    op.drop_table('distillation_memory', schema='legal')
    op.drop_index(op.f('ix_legal_discovery_draft_packs_v2_target_entity'), table_name='discovery_draft_packs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_discovery_draft_packs_v2_status'), table_name='discovery_draft_packs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_discovery_draft_packs_v2_case_slug'), table_name='discovery_draft_packs_v2', schema='legal')
    op.drop_table('discovery_draft_packs_v2', schema='legal')
    op.drop_index(op.f('ix_legal_deposition_kill_sheets_v2_status'), table_name='deposition_kill_sheets_v2', schema='legal')
    op.drop_index(op.f('ix_legal_deposition_kill_sheets_v2_deponent_entity'), table_name='deposition_kill_sheets_v2', schema='legal')
    op.drop_index(op.f('ix_legal_deposition_kill_sheets_v2_case_slug'), table_name='deposition_kill_sheets_v2', schema='legal')
    op.drop_table('deposition_kill_sheets_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_statements_v2_stated_at'), table_name='case_statements_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_statements_v2_entity_id'), table_name='case_statements_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_statements_v2_doc_id'), table_name='case_statements_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_statements_v2_case_slug'), table_name='case_statements_v2', schema='legal')
    op.drop_table('case_statements_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_nodes_v2_entity_type'), table_name='case_graph_nodes_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_nodes_v2_entity_reference_id'), table_name='case_graph_nodes_v2', schema='legal')
    op.drop_index(op.f('ix_legal_case_graph_nodes_v2_case_slug'), table_name='case_graph_nodes_v2', schema='legal')
    op.drop_table('case_graph_nodes_v2', schema='legal')
    op.drop_index(op.f('ix_iot_schema_digital_twins_property_id'), table_name='digital_twins', schema='iot_schema')
    op.drop_index(op.f('ix_iot_schema_digital_twins_device_id'), table_name='digital_twins', schema='iot_schema')
    op.drop_table('digital_twins', schema='iot_schema')
    op.drop_index(op.f('ix_iot_schema_device_events_device_id'), table_name='device_events', schema='iot_schema')
    op.drop_index(op.f('ix_iot_schema_device_events_created_at'), table_name='device_events', schema='iot_schema')
    op.drop_table('device_events', schema='iot_schema')
    op.drop_index('idx_acquisition_parcels_geom', table_name='parcels', schema='crog_acquisition', postgresql_using='gist')
    op.drop_index('idx_acquisition_parcels_assessed', table_name='parcels', schema='crog_acquisition')
    op.drop_table('parcels', schema='crog_acquisition')
    op.drop_index('idx_acquisition_owners_legal_name', table_name='owners', schema='crog_acquisition')
    op.drop_table('owners', schema='crog_acquisition')
    op.drop_index(op.f('ix_core_deliberation_logs_verdict_type'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_session_id'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_reservation_id'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_property_id'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_message_id'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_guest_id'), table_name='deliberation_logs', schema='core')
    op.drop_index(op.f('ix_core_deliberation_logs_created_at'), table_name='deliberation_logs', schema='core')
    op.drop_table('deliberation_logs', schema='core')
    # ### end Alembic commands ###
