"""
Public quote endpoints for guest checkout flows.
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.core.database import get_db
from backend.models.vrs_quotes import GuestQuote, GuestQuoteStatus


router = APIRouter()


class GuestQuoteGenerateRequest(BaseModel):
    property_id: UUID | None = None
    guest_name: str | None = None
    guest_email: str | None = None
    guest_phone: str | None = None
    check_in: date | None = None
    check_out: date | None = None
    adults: int = 2
    children: int = 0
    pets: int = 0
    base_rent: Decimal = Field(default=Decimal("0.00"))
    taxes: Decimal = Field(default=Decimal("0.00"))
    fees: Decimal = Field(default=Decimal("0.00"))
    campaign: str = "direct"
    target_keyword: str | None = None


@router.post("/generate")
async def generate_guest_quote(
    payload: GuestQuoteGenerateRequest,
    db: AsyncSession = Depends(get_db),
):
    nights = None
    if payload.check_in and payload.check_out:
        nights = (payload.check_out - payload.check_in).days
        if nights < 1:
            raise HTTPException(status_code=400, detail="check_out must be after check_in")

    total_amount = payload.base_rent + payload.taxes + payload.fees

    quote = GuestQuote(
        target_property_id=str(payload.property_id) if payload.property_id else "",
        property_id=payload.property_id,
        guest_name=payload.guest_name,
        guest_email=payload.guest_email,
        guest_phone=payload.guest_phone,
        check_in=payload.check_in,
        check_out=payload.check_out,
        nights=nights,
        adults=payload.adults,
        children=payload.children,
        pets=payload.pets,
        base_rent=payload.base_rent,
        taxes=payload.taxes,
        fees=payload.fees,
        total_amount=total_amount,
        base_price=float(payload.base_rent),
        ai_adjusted_price=float(total_amount),
        sovereign_narrative="Autogenerated checkout quote",
        campaign=payload.campaign,
        target_keyword=payload.target_keyword,
        quote_breakdown={
            "base_rent": str(payload.base_rent),
            "taxes": str(payload.taxes),
            "fees": str(payload.fees),
            "total": str(total_amount),
        },
    )
    db.add(quote)
    await db.commit()
    await db.refresh(quote)

    return {
        "id": str(quote.id),
        "status": quote.status,
        "checkout_url": f"/api/quotes/{quote.id}/checkout",
        "total_amount": float(quote.total_amount),
    }


@router.get("/{quote_id}")
async def get_guest_quote(quote_id: UUID, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(GuestQuote).where(GuestQuote.id == quote_id))
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(status_code=404, detail="Quote not found")

    return {
        "id": str(quote.id),
        "status": quote.status,
        "property_id": str(quote.property_id) if quote.property_id else None,
        "guest_name": quote.guest_name,
        "guest_email": quote.guest_email,
        "check_in": str(quote.check_in) if quote.check_in else None,
        "check_out": str(quote.check_out) if quote.check_out else None,
        "nights": quote.nights,
        "total_amount": float(quote.total_amount or 0),
        "stripe_payment_link_url": quote.stripe_payment_link_url,
        "expires_at": str(quote.expires_at) if quote.expires_at else None,
    }


@router.get("/{quote_id}/checkout")
async def quote_checkout_status(quote_id: UUID, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(GuestQuote).where(GuestQuote.id == quote_id))
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(status_code=404, detail="Quote not found")

    return {
        "quote_id": str(quote.id),
        "status": quote.status,
        "is_payable": quote.status == GuestQuoteStatus.PENDING,
        "payment_link_url": quote.stripe_payment_link_url,
        "total_amount": float(quote.total_amount or 0),
    }
