"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Loader2, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

type PackType = "interrogatory" | "rfp" | "admission";

type DiscoveryPackResponse = {
  pack_id: string;
  case_slug: string;
  pack_type: PackType;
  status: string;
  items_generated: number;
  item_limit: number;
  items: string[];
  inference_source?: string;
  breaker_state?: string;
};

type ValidationResponse = {
  pack_id: string;
  items_count: number;
  rule_26_limit: number;
  proportionality_passed: boolean;
};

type DiscoveryDraftPanelProps = {
  slug: string;
};

const PACK_LABELS: Record<PackType, string> = {
  interrogatory: "Interrogatories",
  rfp: "Requests for Production",
  admission: "Requests for Admission",
};

export function DiscoveryDraftPanel({ slug }: DiscoveryDraftPanelProps) {
  const [packType, setPackType] = useState<PackType>("interrogatory");
  const [itemLimit, setItemLimit] = useState(5);
  const [isDrafting, setIsDrafting] = useState(false);
  const [draftPack, setDraftPack] = useState<DiscoveryPackResponse | null>(null);
  const [isValidating, setIsValidating] = useState(false);
  const [rule26Passed, setRule26Passed] = useState<boolean | null>(null);

  const handleDraft = async () => {
    setIsDrafting(true);
    setRule26Passed(null);
    try {
      const response = await api.post<DiscoveryPackResponse>(
        `/api/legal/cases/${slug}/discovery/draft-pack`,
        { pack_type: packType, item_limit: itemLimit },
      );
      const items = Array.isArray(response?.items) ? response.items.map(String) : [];
      setDraftPack({ ...response, items });
      toast.success("Discovery package drafted");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Draft generation failed");
    } finally {
      setIsDrafting(false);
    }
  };

  const handleValidate = async () => {
    if (!draftPack?.pack_id) return;
    setIsValidating(true);
    try {
      const response = await api.post<ValidationResponse>(
        `/api/legal/cases/${slug}/discovery/${draftPack.pack_id}/validate`,
      );
      const passed = Boolean(response?.proportionality_passed);
      setRule26Passed(passed);
      toast.success(passed ? "Rule 26 validation passed" : "Rule 26 validation failed");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Validation failed");
    } finally {
      setIsValidating(false);
    }
  };

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-950/80 p-4 space-y-4">
      <p className="text-sm font-semibold text-zinc-100">Discovery Package Generator</p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <select
          className="h-10 rounded-md border border-input bg-background px-3 text-sm"
          value={packType}
          onChange={(e) => setPackType(e.target.value as PackType)}
        >
          {Object.entries(PACK_LABELS).map(([value, label]) => (
            <option key={value} value={value}>{label}</option>
          ))}
        </select>
        <input
          type="number"
          min={1}
          max={25}
          value={itemLimit}
          onChange={(e) => {
            const next = Number.parseInt(e.target.value, 10);
            setItemLimit(Number.isNaN(next) ? 5 : Math.min(25, Math.max(1, next)));
          }}
          className="h-10 rounded-md border border-input bg-background px-3 text-sm"
          placeholder="Count (max 25)"
        />
        <Button type="button" onClick={handleDraft} disabled={isDrafting}>
          {isDrafting ? (
            <span className="flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" />
              Consulting Swarm...
            </span>
          ) : (
            "Forge Discovery Draft"
          )}
        </Button>
      </div>

      <p className="text-xs text-muted-foreground">
        Max 25 Items &middot; Rule 26 Proportionality Enforced &middot; Human-In-The-Loop Required
      </p>

      {draftPack && Array.isArray(draftPack.items) && draftPack.items.length > 0 && (
        <div className="space-y-3">
          <div className="rounded-md border-2 border-red-600 bg-red-950/60 p-3 flex items-start gap-2">
            <ShieldAlert className="h-5 w-5 text-red-500 shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-bold text-red-400 uppercase tracking-wider">
                Draft Only — Counsel Review Required Prior to Filing or Distribution
              </p>
              <p className="text-xs text-red-300/70 mt-1">
                This material was generated by AI ({draftPack.inference_source ?? "local_dgx"}) and has not been reviewed by licensed counsel.
                Do not file, serve, or distribute without attorney approval.
              </p>
            </div>
          </div>

          {draftPack.inference_source && (
            <div className="flex items-center gap-2 flex-wrap">
              <Badge variant="outline" className="text-[10px]">
                Source: {draftPack.inference_source}
              </Badge>
              {draftPack.breaker_state && (
                <Badge variant="outline" className="text-[10px]">
                  Breaker: {draftPack.breaker_state}
                </Badge>
              )}
            </div>
          )}

          <div className="space-y-2">
            {draftPack.items.map((item, idx) => (
              <div key={`${draftPack.pack_id}-${idx}`} className="rounded border border-zinc-700 bg-zinc-900/70 p-3">
                <p className="text-xs text-zinc-100 leading-relaxed">
                  <span className="text-zinc-500 font-mono mr-2">{String(idx + 1).padStart(2, "0")}.</span>
                  {item}
                </p>
              </div>
            ))}
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <Button type="button" variant="outline" onClick={handleValidate} disabled={isValidating}>
              {isValidating ? (
                <span className="flex items-center gap-2">
                  <Loader2 className="h-3 w-3 animate-spin" />
                  Validating...
                </span>
              ) : (
                "Run Proportionality Validation (Rule 26)"
              )}
            </Button>
            {rule26Passed !== null && (
              <Badge
                variant="outline"
                className={
                  rule26Passed
                    ? "bg-green-500/10 text-green-400 border-green-500/30"
                    : "bg-red-500/10 text-red-400 border-red-500/30"
                }
              >
                Rule 26: {rule26Passed ? "PASS" : "FAIL"}
              </Badge>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
