import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

const signoffMutate = vi.fn();
const reopenMutate = vi.fn();

vi.mock("@/lib/legal-hooks", () => ({
  useCounselSignoffPacket: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-signoff-packet-test",
      packet_version: 1,
      packet_checksum: "abcdef1234567890",
      source_validation_execution_id: "fortress-validation-test",
      source_workbench_execution_id: "fortress-counsel-review-test",
      source_intelligence_execution_id: "fortress-intel-test",
      status: "DRAFT / COUNSEL REVIEW REQUIRED",
      signoff_status: "COUNSEL_SIGNOFF_PENDING",
      readiness_status: "SIGNOFF_PACKET_READY_WITH_UNRESOLVED_ITEMS",
      sections: [
        {
          section_id: "reviewed-issue-matrix",
          title: "Validated / Unvalidated Issue Matrix",
          item_count: 20,
          readiness_status: "incomplete",
          unresolved_count: 20,
          signoff_status: "signoff_pending",
          counsel_review_required: true,
          notes: "Issue packet.",
          source_refs_summary: {
            items: 20,
            with_source_refs: 12,
            without_source_refs: 8,
            total_source_refs: 40,
            locked_restricted_related: 0,
            source_check_status_counts: {},
          },
        },
        {
          section_id: "source-integrity-matrix",
          title: "Source Support / Citation Integrity Matrix",
          item_count: 297,
          readiness_status: "incomplete",
          unresolved_count: 200,
          signoff_status: "signoff_pending",
          counsel_review_required: true,
          notes: "Sources.",
          source_refs_summary: {
            items: 297,
            with_source_refs: 50,
            without_source_refs: 247,
            total_source_refs: 120,
            locked_restricted_related: 0,
            source_check_status_counts: {},
          },
        },
        {
          section_id: "signoff-capture",
          title: "Signoff Page / Signoff Capture Block",
          item_count: 0,
          readiness_status: "not_started",
          unresolved_count: 0,
          signoff_status: "signoff_pending",
          counsel_review_required: true,
          notes: "Explicit signoff required.",
          source_refs_summary: {
            items: 0,
            with_source_refs: 0,
            without_source_refs: 0,
            total_source_refs: 0,
            locked_restricted_related: 0,
            source_check_status_counts: {},
          },
        },
      ],
      source_integrity_matrix: {
        material_items: 297,
        items_with_source_refs: 50,
        items_missing_source_refs: 247,
        items_needing_source_check: 260,
        locked_restricted_source_involved: 2,
        unsupported_assertions_marked_final: false,
        recommended_action: "Source-check before signoff.",
      },
      signoff_readiness_checklist: [
        { check_id: "no-locked-content-used", title: "No locked content used", passed: true },
        { check_id: "signoff-pending", title: "Signoff pending", passed: true },
      ],
      unresolved_items_register: [{ item_id: "issue-01", item_type: "issue_matrix", title: "Issue", validation_status: "needs_counsel_review", source_check_status: "not_checked", counsel_review_required: true }],
      export_snapshot: {
        snapshot_id: "snap-1",
        exportable: true,
        format: "manifest_json",
        contains_document_body_text: false,
        contains_locked_content: false,
      },
      signoff_capture: {
        signoff_recorded: false,
        scope_confirmation_required: true,
      },
      audit_history: [
        { audit_id: "audit-1", action: "signoff_packet_created", created_at: "2026-05-06T12:00:00Z", reviewer_identity_safe_label: "system", reviewer_role: "system" },
      ],
    },
  }),
  useCounselSignoffAction: () => ({ mutate: signoffMutate, isPending: false }),
  useCounselSignoffReopen: () => ({ mutate: reopenMutate, isPending: false }),
  useSourceIntegrity: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-source-integrity-test",
      signoff_packet_execution_id: "fortress-signoff-packet-test",
      source_integrity_summary: {
        total_material_items: 297,
        checked: 297,
        source_verified_for_review_use: 0,
        partially_supported: 0,
        unsupported: 0,
        conflicting_sources: 0,
        wrong_source: 0,
        source_missing: 230,
        needs_page_or_chunk_review: 67,
        locked_or_privilege_limited: 0,
        needs_counsel_review: 0,
        signoff_blockers: 297,
        source_validation_complete_percent: 100,
        verified_subset_count: 0,
        signoff_readiness_recommendation: "READY_FOR_COUNSEL_SOURCE_REVIEW",
        counsel_signoff_pending: true,
      },
      correction_queue: [],
      signoff_blockers: [],
      verified_subset: [],
      batch_results: [],
    },
  }),
  useSourceRemediation: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-source-remediation-test",
      source_integrity_execution_id: "fortress-source-integrity-test",
      signoff_packet_execution_id: "fortress-signoff-packet-test",
      status: "SOURCE_REMEDIATION_COMPLETE_NO_SIGNOFF_SUBSET_READY",
      remediation_summary: {
        total_blockers_processed: 297,
        resolved_source_verified: 0,
        resolved_corrected_for_review_use: 0,
        resolved_duplicate_or_superseded: 0,
        unresolved_partially_supported: 0,
        unresolved_unsupported: 230,
        unresolved_conflicting_sources: 0,
        unresolved_needs_page_or_chunk_review: 65,
        unresolved_needs_more_evidence: 0,
        unresolved_needs_counsel_review: 0,
        unresolved_locked_or_privilege_limited: 2,
        unresolved_wrong_source: 0,
        unable_to_check_safely: 0,
        remaining_blockers: 297,
        verified_subset_count: 0,
        limited_signoff_subset_available: false,
        counsel_signoff_pending: true,
      },
      verified_subset: {
        verified_subset_id: "subset-1",
        item_count: 0,
        item_ids: [],
        packet_sections_covered: [],
        excluded_item_count: 297,
        signoff_scope_recommendation: "NO_LIMITED_SIGNOFF_SUBSET_READY",
        items: [],
      },
      refined_blocker_register: [],
      remediation_category_summary: [],
      signoff_readiness_addendum: {
        readiness_recommendation: "FULL_PACKET_NOT_READY_DUE_TO_UNRESOLVED_BLOCKERS",
        verified_subset_status: "NO_VERIFIED_SUBSET_READY",
        counsel_signoff_pending: true,
        explicit_signoff_recorded: false,
      },
    },
  }),
  useSourceLinkRepair: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-source-link-repair-test",
      source_remediation_execution_id: "fortress-source-remediation-test",
      source_integrity_execution_id: "fortress-source-integrity-test",
      signoff_packet_execution_id: "fortress-signoff-packet-test",
      status: "SOURCE_LINK_REPAIR_COMPLETE_VERIFIED_SUBSET_READY",
      repair_summary: {
        total_blockers_processed: 297,
        verified_for_review_use: 0,
        corrected_verified_for_review_use: 65,
        partially_supported: 0,
        unsupported: 230,
        conflicting_sources: 0,
        needs_page_or_chunk_review: 0,
        needs_more_evidence: 0,
        needs_counsel_review: 0,
        locked_or_privilege_limited: 2,
        unable_to_check_safely: 0,
        remaining_unresolved: 232,
        verified_subset_count: 65,
        counsel_signoff_pending: true,
      },
      packet_section_summary: [],
      verified_subset: {
        verified_subset_id: "subset-2",
        item_count: 65,
        item_ids: ["issue-01"],
        packet_sections_covered: ["issue_matrix"],
        excluded_item_count: 232,
        signoff_scope_recommendation: "LIMITED_SOURCE_LINK_SIGNOFF_REVIEW_SUBSET_AVAILABLE",
        items: [],
      },
      refined_unresolved_register: [],
      signoff_readiness_addendum: {
        readiness_recommendation: "VERIFIED_SUBSET_READY_FOR_COUNSEL_SIGNOFF_REVIEW",
        full_packet_ready: false,
        counsel_signoff_pending: true,
        explicit_signoff_recorded: false,
      },
    },
  }),
  useTargetedSourceCompletion: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-targeted-source-completion-test",
      source_link_repair_execution_id: "fortress-source-link-repair-test",
      source_remediation_execution_id: "fortress-source-remediation-test",
      source_integrity_execution_id: "fortress-source-integrity-test",
      signoff_packet_execution_id: "fortress-signoff-packet-test",
      status: "TARGETED_SOURCE_COMPLETION_VERIFIED_SUBSET_EXPANDED",
      completion_summary: {
        starting_unresolved: 282,
        items_processed: 282,
        prior_verified_subset_count: 15,
        new_items_verified: 50,
        new_verified_subset_count: 65,
        verified_subset_delta: 50,
        remaining_unresolved: 232,
        verified_for_review_use: 0,
        corrected_verified_for_review_use: 50,
        partially_supported: 0,
        unsupported: 230,
        conflicting_sources: 0,
        needs_page_or_chunk_review: 0,
        needs_more_evidence: 0,
        needs_counsel_review: 0,
        locked_or_privilege_limited: 2,
        unable_to_check_safely: 0,
        track_results: {
          track_a_page_chunk_review: { items: 50, verified: 0, corrected: 50, partial: 0, unresolved: 0 },
          track_b_unsupported_recheck: { items: 230, verified: 0, corrected: 0, partial: 0, still_unsupported: 230 },
          track_c_locked_privilege_limited: { items: 2, preserved_metadata_only: 2 },
        },
        counsel_signoff_pending: true,
      },
      packet_section_summary: [],
      expanded_verified_subset: {
        verified_subset_id: "subset-3",
        prior_item_count: 15,
        new_item_count: 65,
        delta: 50,
        item_ids: ["issue-01", "event-01"],
        new_item_ids: ["event-01"],
        packet_sections_covered: ["timeline_event"],
        excluded_item_count: 232,
        signoff_scope_recommendation: "LIMITED_TARGETED_SOURCE_COMPLETION_SIGNOFF_REVIEW_SUBSET_AVAILABLE",
        prior_items: [],
        new_items: [],
      },
      refined_unresolved_register: [],
      signoff_readiness_addendum: {
        targeted_source_completion_execution_id: "fortress-targeted-source-completion-test",
        status: "TARGETED_SOURCE_COMPLETION_COMPLETE",
        verified_subset_status: "VERIFIED_SUBSET_EXPANDED",
        full_packet_ready: false,
        limited_signoff_subset_available: true,
        readiness_recommendation: "LIMITED_SIGNOFF_SUBSET_AVAILABLE",
        counsel_signoff_pending: true,
        explicit_signoff_recorded: false,
      },
    },
  }),
  useLimitedSignoffCandidate: () => ({
    isLoading: false,
    error: null,
    data: {
      execution_id: "fortress-limited-signoff-candidate-test",
      targeted_source_completion_execution_id: "fortress-targeted-source-completion-test",
      source_link_repair_execution_id: "fortress-source-link-repair-test",
      signoff_packet_execution_id: "fortress-signoff-packet-test",
      status: "LIMITED_SIGNOFF_CANDIDATE_PACKET_READY",
      packet_label: "LIMITED_SIGNOFF_CANDIDATE_PACKET",
      governance_labels: ["COUNSEL_REVIEW_REQUIRED", "COUNSEL_SIGNOFF_PENDING"],
      packet_store: "file_manifest",
      verified_subset_used: { item_count: 65, source: "subset-3" },
      high_materiality_source_review: { items_reviewed: 21, items: [] },
      limited_signoff_candidate_packet: {
        candidate_packet_id: "candidate-1",
        included_item_count: 65,
        excluded_item_count: 232,
        included_items: [],
        packet_sections: [],
        section_summary: [],
        signoff_scope_recommendation: "LIMITED_SIGNOFF_CANDIDATE_PACKET_READY_FOR_COUNSEL_REVIEW",
        counsel_signoff_pending: true,
        explicit_signoff_recorded: false,
      },
      unresolved_blocker_register_v2: [],
      tier_summary: {
        tier_1_count: 21,
        tier_2_count: 81,
        tier_3_count: 130,
        excluded_from_packet: 232,
        requires_counsel_interpretation: 16,
        requires_more_evidence: 230,
        locked_privilege_limited: 2,
        unsupported: 230,
        hypothesis_context_only: 0,
      },
      signoff_readiness_addendum: {
        limited_signoff_candidate_execution_id: "fortress-limited-signoff-candidate-test",
        limited_packet_available: true,
        full_packet_ready: false,
        remaining_unresolved: 232,
        readiness_recommendation: "LIMITED_SIGNOFF_CANDIDATE_PACKET_READY_FOR_COUNSEL_REVIEW",
        counsel_signoff_pending: true,
        explicit_signoff_recorded: false,
      },
    },
  }),
  useRemediationMaturity: () => ({
    isLoading: false,
    error: null,
    data: {
      case_slug: "fortress-legal-production-review",
      status: "SOURCE_REMEDIATION_MATURITY_READY_FOR_REVIEW",
      source_manifests: {
        targeted_source_completion_execution_id: "fortress-targeted-source-completion-test",
        limited_signoff_candidate_execution_id: "fortress-limited-signoff-candidate-test",
        source_link_repair_execution_id: "fortress-source-link-repair-test",
        source_remediation_execution_id: "fortress-source-remediation-test",
      },
      governance: {
        counsel_signoff: "COUNSEL_SIGNOFF_PENDING",
        external_submission_authority: "NOT_AUTHORIZED",
        final_legal_conclusions: "NOT_CREATED",
        legal_advice_status: "NOT FINAL LEGAL ADVICE",
        unresolved_items_excluded_from_relied_upon_sections: true,
        locked_restricted_handling: "METADATA_ONLY",
        auto_resolution: "DISABLED",
      },
      remediation_summary: {
        unresolved_total: 232,
        unsupported_or_missing_source: 230,
        locked_restricted_no_review: 2,
        evidence_needed: 230,
        counsel_review_required: 16,
        verified_subset_count: 65,
        limited_packet_available: true,
      },
      classification_counts: {
        by_item_type: [],
        by_materiality_tier: [],
        by_confidence_state: [{ state: "source_missing", count: 230 }],
        by_review_lane: [],
      },
      priority_model: {
        name: "FORTRESS_SOURCE_REVIEW_PRIORITY_V1",
        factors: [],
        automation_boundary: "ranking_only_no_source_resolution",
      },
      priority_queue: [],
      review_workflows: [],
      evidence_lineage: {
        lineage_chain: ["source_integrity", "remediation_maturity_read_model"],
        mutation_model: "read_only_derived_view",
        rollback_model: "git_revert_and_manifest_recheck",
        silent_state_transitions_allowed: false,
      },
      observability: { metrics: [], checker_assertions: [] },
    },
  }),
  useReviewOperations: () => ({
    isLoading: false,
    error: null,
    data: {
      case_slug: "fortress-legal-production-review",
      status: "CONTROLLED_REVIEW_OPERATIONS_READY",
      source_manifests: {
        targeted_source_completion_execution_id: "fortress-targeted-source-completion-test",
        limited_signoff_candidate_execution_id: "fortress-limited-signoff-candidate-test",
        source_link_repair_execution_id: "fortress-source-link-repair-test",
        source_remediation_execution_id: "fortress-source-remediation-test",
      },
      governance: {
        counsel_signoff: "COUNSEL_SIGNOFF_PENDING",
        external_submission_authority: "NOT_AUTHORIZED",
        final_legal_conclusions: "NOT_CREATED",
        legal_advice_status: "NOT FINAL LEGAL ADVICE",
        unresolved_items_excluded_from_relied_upon_sections: true,
        locked_restricted_handling: "METADATA_ONLY",
        auto_resolution: "DISABLED",
        review_operations_mode: "controlled_internal_review_only",
        state_mutation: "read_only_review_operations_view",
      },
      review_operations_summary: {
        unresolved_total: 232,
        remediation_queue_depth: 232,
        contradiction_queue_depth: 14,
        evidence_navigation_items: 90,
        high_priority_items: 21,
        reviewer_owner_unassigned: 232,
        excluded_source_ratio: 1,
        verified_subset_count: 65,
      },
      queues: {
        remediation_review: { summary: { queue_depth: 232 }, items: [] },
        contradiction_review: {
          summary: { queue_depth: 14 },
          severity_levels: [{ level: "critical", rule: "tier_1_high_materiality contradiction" }],
          items: [],
        },
        evidence_navigation: {
          summary: { queue_depth: 90 },
          groups: [{ item_type: "timeline_event", count: 40 }],
          items: [],
        },
        escalation_review: { summary: { queue_depth: 16 }, items: [] },
      },
      review_analytics: {
        confidence_distribution: [{ state: "source_missing", count: 230 }],
        review_lane_distribution: [{ lane: "contradiction_review", count: 14 }],
        item_type_distribution: [{ item_type: "contradiction_candidate", count: 14 }],
        throughput_model: {
          baseline_queue_depth: 232,
          completed_this_phase: 0,
          safe_auto_resolutions: 0,
          human_review_required: 232,
        },
        reviewer_workload_distribution: [{ owner_role_hint: "source_reviewer", count: 214 }],
        sla_distribution: [{ sla_band: "critical_24h", count: 21 }],
        escalation_distribution: [{ escalation_state: "escalate_if_unassigned", count: 21 }],
      },
      reviewer_operations: {
        status: "CONTROLLED_REVIEW_SCALING_READY",
        assignment_model: {
          mode: "derived_reviewer_role_hints_no_persistent_assignment",
          authority_boundary: "queue_manager_may_assign_review_work_no_legal_signoff",
          reviewer_groups: ["operator_reviewer", "source_reviewer", "counsel_or_senior_reviewer"],
          forbidden_assignment_effects: ["source_auto_resolution", "counsel_signoff"],
        },
        workload_balancing: {
          model: "metadata_only_weighted_queue_balancing",
          summary: {
            total_workload_weight: 400,
            unassigned_items: 232,
            counsel_or_senior_reviewer_items: 16,
            source_reviewer_items: 214,
            privilege_metadata_items: 2,
            critical_sla_items: 21,
          },
          distribution: [{ owner_role_hint: "source_reviewer", count: 214 }],
        },
        queue_aging_sla: {
          model: "sla_targets_for_review_attention_only",
          baseline_age_source: "existing_manifest_backlog_no_state_mutation",
          targets: [{ sla_band: "critical_24h", target: "review_owner_assigned_within_24h" }],
          distribution: [{ sla_band: "critical_24h", count: 21 }],
        },
        escalation_governance: {
          model: "human_escalation_only",
          distribution: [{ escalation_state: "escalate_if_unassigned", count: 21 }],
          incident_triggers: ["auth_boundary_failure"],
        },
        incident_readiness: {
          status: "READY_FOR_CONTROLLED_INTERNAL_PILOT",
          rollback_required: true,
          stop_conditions: ["secret_exposure"],
        },
      },
      operational_certification: {
        status: "CONTROLLED_PILOT_OPERATIONS_CERTIFICATION_READY",
        certification_scope: "controlled_internal_reviewer_operations_only",
        readiness_audit: {
          production_route_verified: true,
          authenticated_checker_required: true,
          deployment_verifier_required: true,
          rollback_required: true,
          unresolved_source_issues_excluded: 232,
          counsel_signoff_status: "COUNSEL_SIGNOFF_PENDING",
          external_submission_authority: "NOT_AUTHORIZED",
          final_legal_conclusions: "NOT_CREATED",
          schema_rls_policy_mutation: "NOT_PERFORMED",
        },
        pilot_governance: {
          pilot_mode: "controlled_internal_operations",
          public_launch_enabled: false,
          unrestricted_reviewer_access_enabled: false,
          allowed_operations: ["queue_triage"],
          forbidden_operations: ["auto_signoff", "external_submission"],
        },
        reviewer_onboarding: {
          status: "GOVERNED_ONBOARDING_REQUIRED",
          required_acknowledgments: ["counsel_signoff_pending"],
          allowed_roles: ["operator_reviewer"],
        },
        rollback_certification: {
          status: "ROLLBACK_READY_PENDING_PR_REVIEW",
          git_revertable: true,
          runtime_rollback_required: true,
          verification_after_rollback: ["authenticated_checker"],
        },
        governance_enforcement: {
          status: "ENFORCEMENT_VERIFICATION_REQUIRED_EACH_RUN",
          required_checks: ["COUNSEL_SIGNOFF_PENDING", "NOT_AUTHORIZED"],
        },
        operational_safety: {
          status: "CERTIFIED_FOR_CONTROLLED_INTERNAL_PILOT_REVIEW",
          certification_limitations: ["no_public_launch"],
        },
      },
      internal_pilot: {
        status: "CONTROLLED_INTERNAL_PILOT_READY",
        pilot_mode: "read_only_synthetic_and_metadata_safe",
        execution_scope: "controlled_internal_reviewer_operations",
        pilot_summary: {
          review_queue_depth: 232,
          remediation_triage_items: 232,
          contradiction_review_items: 14,
          evidence_navigation_items: 90,
          escalation_items: 21,
          unresolved_source_issues: 232,
          excluded_source_issues: 232,
          locked_restricted_metadata_only: 2,
          pilot_completion_readiness: "READY_FOR_CONTROLLED_INTERNAL_USE_ONLY",
        },
        allowed_exercises: ["read_only_review_queue_traversal"],
        forbidden_exercises: ["legal_signoff", "external_submission"],
        throughput_metrics: {
          queue_depth: 232,
          queue_aging_bands: [{ sla_band: "critical_24h", count: 21 }],
          review_traversal_sample: 40,
          remediation_triage_count: 232,
          contradiction_review_count: 14,
          evidence_navigation_count: 90,
          reviewer_handoff_count: 4,
          escalation_count: 21,
          unresolved_source_count: 232,
          excluded_source_count: 232,
          confidence_distribution: [{ state: "source_missing", count: 230 }],
        },
        pilot_drills: [
          { scenario: "unsupported_assertion_seen", expected_response: "keep_excluded_and_route_to_source_reviewer" },
        ],
        ergonomic_optimizations: ["single_pilot_summary"],
        governance: {
          counsel_signoff: "COUNSEL_SIGNOFF_PENDING",
          external_submission_authority: "NOT_AUTHORIZED",
          legal_advice_status: "NOT FINAL LEGAL ADVICE",
          final_legal_conclusions: "NOT_CREATED",
          schema_rls_policy_mutation: "NOT_PERFORMED",
          contains_document_body_text: false,
          contains_locked_content: false,
          production_writes: "none",
        },
      },
      pilot_readiness: {
        controlled_internal_review_ready: true,
        public_or_external_use_enabled: false,
        required_controls: ["authenticated_staff_access"],
        forbidden_operations: ["auto_signoff"],
      },
      observability: {
        checker_assertions: ["review_operations_visible"],
        metrics: ["remediation_queue_depth"],
      },
    },
  }),
}));

import { CounselSignoffStrategyPacket } from "@/app/(dashboard)/legal/cases/[slug]/_components/counsel-signoff-strategy-packet";

describe("CounselSignoffStrategyPacket", () => {
  it("renders strategy packet, source integrity, pending signoff, and requires scope confirmation", () => {
    render(<CounselSignoffStrategyPacket slug="fortress-legal-production-review" />);

    expect(screen.getByText("Strategy Packet / Counsel Signoff")).toBeInTheDocument();
    expect(screen.getAllByText("DRAFT / COUNSEL REVIEW REQUIRED").length).toBeGreaterThan(0);
    expect(screen.getAllByText("NOT FINAL LEGAL CONCLUSION").length).toBeGreaterThan(0);
    expect(screen.getByText("Validated / Unvalidated Issue Matrix")).toBeInTheDocument();
    expect(screen.getByText("Source Integrity Matrix")).toBeInTheDocument();
    expect(screen.getByText("Source Blocker Remediation")).toBeInTheDocument();
    expect(screen.getByText("Source Link Repair")).toBeInTheDocument();
    expect(screen.getByText("Targeted Source Completion")).toBeInTheDocument();
    expect(screen.getByText("Limited Signoff Candidate Packet")).toBeInTheDocument();
    expect(screen.getByText("Remediation Maturity / Review Queue")).toBeInTheDocument();
    expect(screen.getByText("Controlled Review Operations")).toBeInTheDocument();
    expect(screen.getByText(/Export snapshot contains no document body text and no locked content/)).toBeInTheDocument();

    const operatorButton = screen.getByText("Operator Acknowledge");
    expect(operatorButton).toBeDisabled();

    fireEvent.click(screen.getByLabelText(/approved review scope only/i));
    fireEvent.click(operatorButton);

    expect(signoffMutate).toHaveBeenCalledWith({
      signoff_type: "operator_review_acknowledgment",
      scope_confirmed: true,
      notes: "Operator review acknowledgment captured from Strategy Packet panel.",
    });
  });
});
